name = "vzome-playground"
compatibility_date = "2026-06-01"
main = "worker/index.js"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

# Sketch storage (KV namespace "SKETCHES").
[[kv_namespaces]]
binding = "SKETCHES"
id = "e664729a3a1c4c5699fa361c62cad248"
